apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
  labels:
    app: citus
    role: coordinator
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: citus
    role: coordinator

---
apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  labels:
    app: citus
    role: worker
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: citus
    role: worker

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-coordinator
  labels:
    app: citus
    role: coordinator
spec:
  serviceName: citus-coordinator
  replicas: 1
  selector:
    matchLabels:
      app: citus
      role: coordinator
  template:
    metadata:
      labels:
        app: citus
        role: coordinator
    spec:
      containers:
        - name: postgres
          image: citusdata/citus:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: citus-secret
                  key: POSTGRES_PASSWORD
            - name: CITUS_NODE_ROLE
              value: "coordinator"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: coordinator-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: coordinator-data
          emptyDir: {}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker
  labels:
    app: citus
    role: worker
spec:
  serviceName: citus-worker
  replicas: 2
  selector:
    matchLabels:
      app: citus
      role: worker
  template:
    metadata:
      labels:
        app: citus
        role: worker
    spec:
      containers:
        - name: postgres
          image: citusdata/citus:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: citus-secret
                  key: POSTGRES_PASSWORD
            - name: CITUS_NODE_ROLE
              value: "worker"
            - name: CITUS_MASTER_HOST
              value: "citus-coordinator"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: worker-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: worker-data
          emptyDir: {}
