services:
  controller:
    image: citusdata/citus:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      CITUS_NODE_ROLE: coordinator
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1

  worker:
    image: citusdata/citus:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      CITUS_NODE_ROLE: worker
      CITUS_MASTER_HOST: controller
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 2
