services:
  controller:
    build:
      context: .
    container_name: citus-controller
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      CITUS_NODE_ROLE: coordinator
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  worker1:
    build:
      context: .
    container_name: citus-worker-01
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      CITUS_NODE_ROLE: worker
      CITUS_MASTER_HOST: controller
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  worker2:
    build:
      context: .
    container_name: citus-worker-02
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      CITUS_NODE_ROLE: worker
      CITUS_MASTER_HOST: controller
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
