services:
  controller:
    image: citusdata/citus:latest
    container_name: citus_controller
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CITUS_NODE_ROLE: coordinator
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker1:
    image: citusdata/citus:latest
    container_name: citus_worker1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CITUS_NODE_ROLE: worker
      CITUS_MASTER_HOST: controller
    depends_on:
      - controller

  worker2:
    image: citusdata/citus:latest
    container_name: citus_worker2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CITUS_NODE_ROLE: worker
      CITUS_MASTER_HOST: controller
    depends_on:
      - controller
